<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Adds a backpack with progressively larger storage capacity</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
    <ProjectReference Include="..\ServersideQoL.Player\ServersideQoL.Player.csproj" Aliases="Player" Private="False" PrivateAssets="all" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
