<Project>
	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<DebugSymbols>true</DebugSymbols>
		<DebugType>embedded</DebugType>
		<MinVerTagPrefix>v</MinVerTagPrefix>
		<MinVerDefaultPreReleaseIdentifiers>beta.0</MinVerDefaultPreReleaseIdentifiers>
		<ValheimDir>$(USERPROFILE)\Games\valheim\</ValheimDir>
		<Authors>ArgusMagnus</Authors>
		<Copyright>$(Authors)</Copyright>
		<RepositoryUrl>https://github.com/ArgusMagnus/ValheimServersideQoL</RepositoryUrl>
		
		<Version>2.0.0-beta.1</Version>

    <DependencyDirectory>$(MSBuildThisFileDirectory)Dependencies\</DependencyDirectory>
	</PropertyGroup>

  <PropertyGroup Condition="$(MSBuildProjectName.Contains('.CodeAnalysis')) == 'false' AND $(MSBuildProjectName.Contains('.Patcher')) == 'false'">
    <CreatePackage>true</CreatePackage>
  </PropertyGroup>

  <ItemGroup Condition="'$(CreatePackage)' == 'true'">
    <None Include="$(MSBuildProjectDirectory)\icon.png" CopyToOutputDirectory="Always" />
    <None Include="$(MSBuildProjectDirectory)\README.md" CopyToOutputDirectory="Always" />
    <None Include="$(MSBuildProjectDirectory)\CHANGELOG.md" CopyToOutputDirectory="Always" />
  </ItemGroup>  
  
</Project>