<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Automatically update map tables with icons for portals, ships, ore deposits and more.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
  </ItemGroup>

</Project>
