<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Ballista don't target players or tames and reload from nearby containers.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
  </ItemGroup>

</Project>
