<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Teleport followers (tamed or summoned creatures) to the player if they get left behind. Take them through portals or into dungeons.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
  </ItemGroup>

</Project>
