<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Introduces additional effects with increasing player skill levels</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
  </ItemGroup>

</Project>
