<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Allows progressively more ores/metals to be taken through portals after bosses are defeated</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
  </ItemGroup>

</Project>
