<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Remove Mistland's mist. Configure trader progression requirements. And more to come (maybe).</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
  </ItemGroup>

</Project>
