<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Lets all sinking items float by putting them into cargo crates when they sink too deep</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
    <ProjectReference Include="..\ServersideQoL.AutoStore\ServersideQoL.AutoStore.csproj" Aliases="AutoStore" Private="False" PrivateAssets="all" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
