<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Gives admins the ability to change various build/landscaping options for themselves</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
  </ItemGroup>

</Project>
