<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Automatically feeds processing stations such as smelters, kilns, windmills, shield generators, etc. from nearby containers</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
  </ItemGroup>

</Project>
