<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Automatically feeds processing stations such as smelters, kilns, windmills, shield generators, etc. from nearby containers</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
    <ProjectReference Include="..\ServersideQoL.ContainerSigns\ServersideQoL.ContainerSigns.csproj" Aliases="ContainerSigns" Private="False" PrivateAssets="all" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
