<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Various multiplayer tweaks. Networking options which help reduce the experienced effects of lag. Force map player pins to always be on.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
  </ItemGroup>

</Project>
