<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Description>Automatically put dropped items and items in player inventories into nearby containers</Description>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
	</ItemGroup>

</Project>
