<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Configure the max level of creature and let it increase with world progression</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
  </ItemGroup>

</Project>
