<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Make all container inventory sizes configurable and optionally let the grow infinitely if the contain only one item type</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
  </ItemGroup>

</Project>
