<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Adds signs to chests and barrels. Optionally show automated content list and configure the container for other SQoL mods.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
  </ItemGroup>

</Project>
