<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Description>Show in-game time on signs, set default sign color and put signs showing the remaining fermentation time on fermenters</Description>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
	</ItemGroup>
	
</Project>
