<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Supercharges the wishbone so it can find dungeons, vegvisirs and configurably more.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
  </ItemGroup>

</Project>
